// students.js - Data siswa berdasarkan absensi resmi
const STUDENTS_DATA = [
    { nama: "AI MUHLIAWATI", foto: "AI_MUHLIAWATI.jpg", jenisKelamin: "Perempuan" },
    { nama: "ALIN NUR ALIAH", foto: "ALIN_NUR_ALIAH.jpg", jenisKelamin: "Perempuan" },
    { nama: "ALYA PUTRI NURAENI", foto: "ALYA_PUTRI_NURARENI.jpg", jenisKelamin: "Perempuan" },
    { nama: "AZIS MAULANA", foto: "AZIS_MAULANA.jpg", jenisKelamin: "Laki-laki" },
    { nama: "DAVIAN GUSTI AGRAPRANA", foto: "DAVIAN_GUSTI_AGRAPRANA.jpg", jenisKelamin: "Laki-laki" },
    { nama: "DEP FRANS PURNAMALILA KOSASIH", foto: "DEP_FRANS_PURNAMALILA_KOSASIH.jpg", jenisKelamin: "Laki-laki" },
    { nama: "DZAKI DZIYA DZAIFULLOH", foto: "DZAKI_DZIYA_DZAIFULLOH.jpg", jenisKelamin: "Laki-laki" },
    { nama: "FINO AGUSTIANI ROMADON", foto: "FINO_AGUSTIANI_ROMADHON.jpg", jenisKelamin: "Laki-laki" },
    { nama: "FIRMAN HIDAYAT", foto: "FIRMAN_HIDAYAT.jpg", jenisKelamin: "Laki-laki" },
    { nama: "IRZA RADITYA DARMAWAN", foto: "IRZA_RADITYA_DARMAWAN.jpg", jenisKelamin: "Laki-laki" },
    { nama: "IYAN HIDAYAT", foto: "IYAN_HIDAYAT.jpg", jenisKelamin: "Laki-laki" },
    { nama: "MOCH RIFKA AL FARIZ", foto: "MOCH_RIFKA_AL_FARIZ.jpg", jenisKelamin: "Laki-laki" },
    { nama: "MUHAMMAD AFGHAN AL KHAWARIZMI", foto: "MUHAMMAD_AFGHAN_AL_KHAWARIZMI.jpg", jenisKelamin: "Laki-laki" },
    { nama: "NAZHAR PADILLAH", foto: "NAZHAR_PADLAN.jpg", jenisKelamin: "Laki-laki" },
    { nama: "NEZHLA AGUSTIN NURHALIZA", foto: "NEZHLA_AGUSTIN_NURHALIZA.jpg", jenisKelamin: "Perempuan" },
    { nama: "NINDA DWIYANTI SOMANTRI", foto: "NINDA_DWIYANTI_SOMANTRI.jpg", jenisKelamin: "Perempuan" },
    { nama: "NOFAL EKACAHYADI", foto: "NOFAL_EKACHYADI.jpg", jenisKelamin: "Laki-laki" },
    { nama: "RAFFI MAULANA", foto: "RAFI_MAULANA.jpg", jenisKelamin: "Laki-laki" },
    { nama: "RAFI MUHAMMAD RODLIANI", foto: "RAFI_MUHAMMAD_RODLIANI.jpg", jenisKelamin: "Laki-laki" },
    { nama: "REZKY NUR AZMI YUDIANA", foto: "REZKY_NUR_AZMI_YUDIANA.jpg", jenisKelamin: "Laki-laki" },
    { nama: "RIZKI ADHAYANI", foto: "RIZKI_ADHAYANI.jpg", jenisKelamin: "Laki-laki" },
    { nama: "ROMY ADITIYA PERMANA", foto: "ROMY_ADHITYA_PERMANA.jpg", jenisKelamin: "Laki-laki" },
    { nama: "SAEPULOH", foto: "SAEPULOH.jpg", jenisKelamin: "Laki-laki" },
    { nama: "SAUPIYAN TSAURI", foto: "SAUPIYAN_TSAURI.jpg", jenisKelamin: "Laki-laki" },
    { nama: "SELPI", foto: "SELPI.jpg", jenisKelamin: "Perempuan" },
    { nama: "SIGITH SUGIARTO", foto: "SIGITH_SUGIARTO.jpg", jenisKelamin: "Laki-laki" },
    { nama: "SYIFA RAHILA NURHARITSA", foto: "SYIFA_RAHILA_NURHARITS.jpg", jenisKelamin: "Perempuan" },
    { nama: "VITA NOVIA", foto: "VITA_NOVIA.jpg", jenisKelamin: "Perempuan" },
    { nama: "YORIS YANUAR FAJAR ALI", foto: "YORIS_YANUAR_FAJAR_ALI.jpg", jenisKelamin: "Laki-laki" },
    { nama: "YUNI FEBRIYANI", foto: "YUNI_FEBRIYANI.jpg", jenisKelamin: "Perempuan" }
];
